home/urls.py
from django.urls import path

from . import views

urlpatterns = [
    # ex: /home/
    path('', views.index, name='index'),

]

myProject1/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from home import views

urlpatterns = [
    path('', include('home.urls')),
    path('house/', include('house.urls')),
    path('user/', include('user.urls')),
    path('admin/', admin.site.urls),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('hakkimizda/', views.hakkimizda, name='hakkimizda'),
    path('referanslar/', views.referanslar, name='referanslar'),
    path('iletisim/', views.iletisim, name='iletisim'),
    path('category/<int:id>/<slug:slug>/',views.category_houses, name='category_houses'),
    path('house/<int:id>/<slug:slug>/',views.house_detail, name='house_detail'),
    path('search/', views.house_search, name='house_search'),
    path('search_auto/', views.house_search_auto, name='house_search_auto'),
    path('logout/', views.logout_view, name='logout_view'),
    path('login/', views.login_view, name='login_view'),
    path('signup/', views.signup_view, name='signup_view'),
    path('sss/', views.faq, name='faq'),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/models.py
from ckeditor_uploader.fields import RichTextUploadingField
from django.contrib.auth.models import User
from django.db import models

# Create your models here.
from django.forms import ModelForm, TextInput, Textarea
from django.utils.safestring import mark_safe


class Setting(models.Model):
    STATUS = (
        ('True', 'Evet'),
        ('False', 'Hayır'),
    )
    title = models.CharField(max_length=150)
    keywords = models.CharField(blank=True,max_length=255)
    description = models.CharField(blank=True,max_length=255)
    company = models.CharField(max_length=150)
    address = models.CharField(blank=True, max_length=150)
    phone = models.CharField(blank=True, max_length=15)
    fax = models.CharField(blank=True, max_length=15)
    email = models.CharField(blank=True, max_length=50)
    smptserver = models.CharField(blank=True,max_length=20)
    smptpemail = models.CharField(blank=True,max_length=20)
    smptppassword = models.CharField(blank=True,max_length=10)
    smtpport = models.CharField(blank=True, max_length=5)
    icon = models.ImageField(blank=True, upload_to='images/')
    facebook = models.CharField(blank=True,max_length=50)
    instagram = models.CharField(blank=True,max_length=50)
    twitter = models.CharField(blank=True,max_length=50)
    aboutus = RichTextUploadingField(blank=True)
    contact = RichTextUploadingField(blank=True)
    references = RichTextUploadingField(blank=True)
    status = models.CharField(max_length=10, choices=STATUS)
    create_at = models.DateTimeField(auto_now_add=True)
    update_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title

class ContactFormMessage(models.Model):
    STATUS = (
        ('New', 'New'),
        ('Read', 'Read'),
        ('Closed','Closed'),
    )
    name = models.CharField(blank=True, max_length=20)
    email = models.CharField(blank=True, max_length=50)
    subject = models.CharField(blank=True,max_length=50)
    message = models.CharField(blank=True,max_length=255)
    status = models.CharField(max_length=10, choices=STATUS, default='New')
    ip = models.CharField(blank=True, max_length=20)
    note = models.CharField(blank=True, max_length=100)
    create_at = models.DateTimeField(auto_now_add=True)
    update_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name

class ContactFormu(ModelForm):
    class Meta:
        model = ContactFormMessage
        fields = ['name', 'email', 'subject', 'message']
        widgets = {
            'name': TextInput(attrs={'class=table table-bordered table-condensed': 'input', 'placeholder': 'Name & Surname'}),
            'email': TextInput(attrs={'class=table table-bordered table-condensed': 'input', 'placeholder': 'Email'}),
            'subject': TextInput(attrs={'class=table table-bordered table-condensed': 'input', 'placeholder': 'Email Address'}),
            'message': Textarea(attrs={'class=table table-bordered table-condensed': 'input', 'placeholder': 'Your Message', 'rows': '5'}),
        }

class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    phone = models.CharField(blank=True, max_length=20)
    address = models.CharField(blank=True, max_length=150)
    city = models.CharField(blank=True, max_length=20)
    country = models.CharField(blank=True, max_length=20)
    image = models.ImageField(blank=True, upload_to='images/users/')

    def __str__(self):
        return self.user.username

    def user_name(self):
        return self.user.first_name + ' '+self.user.last_name + ' [ ' +self.user.username + ' ] '

    def image_tag(self):
        return mark_safe('<img src="{}" height="50" />'.format(self.image.url))

    image_tag.short_description = 'Image'


class UserProfileForm(ModelForm):
    class Meta:
        model = UserProfile
        fields = ['phone', 'address', 'city', 'country', 'image']


class FAQ(models.Model):
    STATUS = (
        ('True', 'Evet'),
        ('False', 'Hayır'),
    )
    ordernumber = models.IntegerField()
    question = models.CharField(max_length=150)
    answer = models.TextField()
    status = models.CharField(max_length=10, choices=STATUS)
    create_at = models.DateTimeField(auto_now_add=True)
    update_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.question

house/models.py
from ckeditor.widgets import CKEditorWidget
from django.contrib.auth.models import User
from django.db import models

# Create your models here.
from django.forms import ModelForm, TextInput, Select, FileInput
from django.urls import reverse
from django.utils.safestring import mark_safe
from ckeditor_uploader.fields import RichTextUploadingField
from mptt.fields import TreeForeignKey
from mptt.models import MPTTModel


class Category(MPTTModel):
    STATUS = (
        ('True', 'Evet'),
        ('False' , 'Hayır'),
    )
    title = models.CharField(blank=True, max_length=100)
    keywords = models.CharField(blank=True, max_length=255)
    description = models.CharField(blank=True, max_length=255)
    image = models.ImageField(upload_to='images/')
    status = models.CharField(max_length=10, choices=STATUS)
    slug = models.SlugField(null=False, unique=True)
    parent = TreeForeignKey('self',blank=True, null=True, related_name='children', on_delete=models.CASCADE)
    create_up = models.DateTimeField(auto_now_add=True)
    update_up = models.DateTimeField(auto_now=True)

    class MPTTMeta:
        order_insertion_by = ['title']

    def __str__(self):
        full_path = [self.title]
        k = self.parent
        while k is not None:
            full_path.append(k.title)
            k = k.parent
        return ' / '.join(full_path[::-1])

    def image_tag(self):
        return mark_safe('<img src="{}" height="50"/>'.format(self.image.url))
    image_tag.short_description = 'Image'

    def get_absolute_url(self):
        return reverse('category_detail', kwargs={'slug': self.slug})

class House(models.Model):
    STATUS = (
        ('True', 'Evet'),
        ('False' , 'Hayır'),
    )
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    category = models.ForeignKey(Category, on_delete=models.CASCADE) #relation with Category table
    title = models.CharField(max_length=150)
    keywords = models.CharField(blank=True,max_length=255)
    description = models.CharField(blank=True,max_length=255)
    address = models.CharField(blank=True,max_length=255)
    image = models.ImageField(upload_to='images/',blank=True)
    price = models.FloatField(blank=True,null=True)
    detail = RichTextUploadingField()
    slug = models.SlugField(null=False, unique=True)
    room = models.IntegerField(blank=True,null=True)
    floor = models.IntegerField(blank=True,null=True)
    m2 = models.IntegerField(blank=True,null=True)
    status = models.CharField(max_length=10, choices=STATUS)
    create_at = models.DateTimeField(auto_now_add=True)
    update_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title

    def image_tag(self):
        return mark_safe('<img src="{}" height="50"/>'.format(self.image.url))
    image_tag.short_description = 'Image'

    def get_absolute_url(self):
        return reverse('house_detail', kwargs={'slug': self.slug})
class HouseForm(ModelForm):
    class Meta:
        model = House
        fields = ['category', 'title', 'slug', 'keywords', 'description', 'image', 'detail']
        widgets = {
            'title': TextInput(attrs={'class': 'input', 'placeholder': 'title'}),
            'slug': TextInput(attrs={'class': 'input', 'placeholder': 'slug'}),
            'keywords': TextInput(attrs={'class': 'input', 'placeholder': 'keywords'}),
            'description': TextInput(attrs={'class': 'input', 'placeholder': 'description'}),
            'category': Select(attrs={'class': 'input', 'placeholder': 'type'}, choices=Category.objects.all()),
            'image': FileInput(attrs={'class': 'input', 'placeholder': 'image'}),
            'detail': CKEditorWidget(),
        }

class Images(models.Model):
    house = models.ForeignKey(House, on_delete=models.CASCADE)
    title = models.CharField(max_length=50, blank=True)
    image = models.ImageField(blank=True, upload_to='images/')

    def __str__(self):
        return self.title

    def image_tag(self):
        return mark_safe('<img src="{}" height="50"/>'.format(self.image.url))
    image_tag.short_description = 'Image'

class ImageForm(ModelForm):
    class Meta:
        model = Images
        fields = ['title', 'image']

class Comment(models.Model):
    STATUS = (
        ('New', 'Yeni'),
        ('True', 'Evet'),
        ('False' , 'Hayır'),
    )
    house = models.ForeignKey(House, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    subject = models.CharField(max_length=50)
    comment = models.TextField(blank=True, max_length=200)
    rate = models.IntegerField(blank=True, null=True)
    status = models.CharField(max_length=10, choices=STATUS, default='New')
    ip = models.CharField(blank=True,max_length=20)
    create_up = models.DateTimeField(auto_now_add=True)
    update_up = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.subject

class CommentForm(ModelForm):
    class Meta:
        model = Comment
        fields = ['subject', 'comment', 'rate']

home/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class SearchForm(forms.Form):
    query = forms.CharField(label="Search", max_length=100)

class SignUpForm(UserCreationForm):
    username = forms.CharField(max_length=30, label='User Name :')
    email = forms.EmailField(max_length=200, label='Email :')
    first_name = forms.CharField(max_length=100, label='First Name :')
    last_name = forms.CharField(max_length=100,  label='Last Name :')

    class Meta:
        model = User
        fields = ('username', 'email', 'first_name', 'last_name', 'password1', 'password2',)

home/views.py
import json

from django.contrib import messages
from django.contrib.auth import logout, authenticate, login
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render

# Create your views here.
from home.forms import SearchForm, SignUpForm
from home.models import Setting, ContactFormu, ContactFormMessage, UserProfile, FAQ
from house.models import Category, House, Images, Comment


def index(request):
    setting = Setting.objects.get(pk=1)
    sliderdata = House.objects.all()[:6]
    category = Category.objects.all()
    dayhouses = House.objects.all()[:6]
    randomhouses = House.objects.all().order_by('?')[:4]

    context = {'setting': setting,
               'category': category,
               'page':'home',
               'sliderdata': sliderdata,
               'dayhouses': dayhouses,
               'randomhouses': randomhouses
               }
    return render(request, 'index.html', context)


def hakkimizda(request):
    setting = Setting.objects.get(pk=1)
    category = Category.objects.all()

    context = {'setting': setting,
               'category': category,
               'page':'hakkimizda'}
    return render(request, 'hakkimizda.html', context)

def referanslar(request):
    setting = Setting.objects.get(pk=1)
    category = Category.objects.all()

    context = {'setting': setting,
               'category': category,
               'page':'referanslar'}
    return render(request, 'referanslar.html', context)


def iletisim(request):
    category = Category.objects.all()
    if request.method == 'POST':  # form post edildiyse
        form = ContactFormu(request.POST)
        if form.is_valid():
            data = ContactFormMessage()  # model ile bağlantı kur
            data.name = form.cleaned_data['name']  # formdan bilgiyi al
            data.email = form.cleaned_data['email']
            data.subject = form.cleaned_data['subject']
            data.message = form.cleaned_data['message']
            data.ip = request.META.get('REMOTE_ADDR')
            data.save()  # veritabanına kaydet
            messages.success(request, "Mesajınız başarı ile gönderilmiştir. Teşekkür Ederiz")
            return HttpResponseRedirect('/iletisim')
    setting = Setting.objects.get(pk=1)
    form = ContactFormu()
    context = {'setting': setting, 'category': category, 'form': form}
    return render(request, 'iletisim.html', context)

def category_houses(request, id,slug):
    category = Category.objects.all()
    categorydata = Category.objects.get(pk=id)
    if slug == "child":
        houses = House.objects.filter(category_id=id)
    else:
        houses = House.objects.filter(category__parent_id=id)

    context = {'houses' : houses,
               'categorydata': categorydata,
               'category': category
               }
    return render(request, 'evler.html', context)


def house_detail(request, id, slug):
    category = Category.objects.all()
    house = House.objects.get(pk=id)
    images = Images.objects.filter(house_id=id)
    comments = Comment.objects.filter(house_id=id, status= 'True')
    contenthouses = House.objects.all()[:4]

    context = {'house': house,
                'category': category,
               'images' : images,
               'comment' : comments,
               'contenthouses': contenthouses
               }
    return render(request, 'house_detail.html', context)

def house_search(request):
    if request.method == 'POST':
        form = SearchForm(request.POST)
        if form.is_valid():
            category = Category.objects.all()
            query = form.cleaned_data['query']
            houses = House.objects.filter(title__icontains=query)
            context = {
                'category': category,
                'houses': houses,
            }
            return render(request, 'house_search.html', context)
    return HttpResponseRedirect('/')

def house_search_auto(request):
    if request.is_ajax():
        q = request.GET.get('term', '')
        house = House.objects.filter(title__icontains=q)
        results = []
        for rs in house:
            house_json = {}
            house_json = rs.title
            results.append(house_json)
        data = json.dumps(results)
    else:
        data = 'fail'
    mimetype = 'application/json'
    return HttpResponse(data, mimetype)


def logout_view(request):
    logout(request)
    return HttpResponseRedirect('/')

def login_view(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            messages.success(request, "Hoşgeldiniz")
            return HttpResponseRedirect('/')
        else:
            messages.warning(request, "Login Hatası ! Kullanıcı adı ya da şifre yanlış")
            return HttpResponseRedirect('/login')

    category = Category.objects.all()
    context = {
        'category': category,
    }
    return render(request, 'login.html', context)


def signup_view(request):
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=password)
            login(request, user)
            #create data in profile table for user
            current_user = request.user
            data = UserProfile()
            data.user_id = current_user.id
            data.image = "images/users/user.png"
            data.save()
            messages.success(request,
                "Hoş Geldiniz.. Kendi ev kiralama siteme başarılı bir şekilde üye oldunuz.İyi gezinmeler dilerim.")
            return HttpResponseRedirect('/')

    form = SignUpForm()
    category = Category.objects.all()
    context = {
        'category': category,
        'form': form,
    }
    return render(request, 'signup.html', context)

def faq(request):
    setting = Setting.objects.get(pk=1)
    category = Category.objects.all()
    faq = FAQ.objects.all().order_by('ordernumber')
    context = {
        'category': category,
        'setting': setting,
        'faq': faq,
    }
    return render(request, 'faq.html', context)

home/templates/evler.html
{% extends "homebase.html" %}
{% block title %}{{ setting.company }} {% endblock %}
{% block keywords %}{{ setting.keywords }}{% endblock %}
{% block description %}{{ setting.description }}{% endblock %}



{% block header %}
    {% include 'header.html' %}
    <link rel='shortcut icon' type='image/x-icon' href='{{ setting.icon.url }}' />
{% endblock %}



{% block content %}
    <div class="hero-wrap" style="background-image: url('../static/images/bg_1.jpg');">
        <div class="overlay"></div>
        <div class="container">
            <div class="row no-gutters slider-text align-items-center justify-content-center">

                    <div class="col-md-9 ftco-animate text-center">
                        <p class="breadcrumbs"><span class="mr-2"><a href="/">Anasayfa</a></span></p>
                        <h1 class="mb-3 bread">{{ categorydata.title }}</h1>
                    </div>

            </div>
        </div>
    </div>

    <section class="ftco-section bg-light">

        <div class="container">
            <div class="row">
                {% for rs in houses %}
                    <div class="col-md-4 ftco-animate">

                        <div class="properties">

                            <a href="/house/{{ rs.id }}/{{ rs.slug }}" class="img img-2 d-flex justify-content-center align-items-center" style="background-image: url({{ rs.image.url }});">
                                <div class="icon d-flex justify-content-center align-items-center">
                                    <span class="icon-search2"></span>
                                </div>
                            </a>
                            <div class="text p-3">
                                <span class="status sale">{{rs.description}}</span>
                                <div class="d-flex">
                                    <div class="one">
                                        <h3><a href="/houses">{{rs.address}}</a></h3>
                                        <p>{{ rs.title }}</p>
                                    </div>
                                    <div class="two">
                                        <span class="price">{{ rs.price }}</span>
                                    </div>
                                </div>
                                <p>{{ rs.detail|safe }}</p>
                                <hr>
                                <p class="bottom-area d-flex">
                                    <span><i class="flaticon-selection"></i>{{ rs.m2 }}</span>
                                    <span class="ml-auto"><i class="flaticon-house"></i> {{ rs.room }}</span>
                                </p>
                            </div>

                        </div>

                    </div>
                {% endfor %}
            </div>
        </div>

    </section>
{% endblock %}


{% include 'footer.html' %}



{% block footer %} {% endblock %}

home/templates/faq.html
{% extends "homebase.html" %}
{% block title %}Sıkça Sorulan Sorular{% endblock %}
{% block keywords %}  {% endblock %}
{% block description %}  {% endblock %}

{% block header %}
    {% include 'header.html' %}
    <link rel='shortcut icon' type='image/x-icon' href='{{ setting.icon.url }}' />
    <script>
        $(function () {
            $("#accordion").accordion();
        });
    </script>
{% endblock %}


{% block content %}


    <!-- bradcam_area_start -->
    <div class="bradcam_area breadcam_bg overlay2">

    </div>
    <!-- bradcam_area_end -->

    <!-- about_area_start -->
    <div class="about_area">
        <div class="container">
            <div class="row">
                <div id="accordion"><h3>Sıkça Sorulan Sorular</h3>
                    {% for rs in faq %}
                        <h5>
                            {{ rs.question }}
                        </h5>
                        <div>
                            <p>{{ rs.answer }}</p>
                        </div>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>

    <!-- about_area_end -->






{% endblock %}

{% include 'footer.html' %}
{% block footer %} {% endblock %}

home/templates/footer.html
<footer class="ftco-footer ftco-bg-dark ftco-section">
    <div class="container">
        <div class="row mb-2">
            <div class="col-md">
                <div class="ftco-footer-widget mb-4">
                    <h2 class="ftco-heading-2">SadolifeEvKiralama</h2>
                    <p>Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.</p>
                    <ul class="ftco-footer-social list-unstyled float-md-left float-lft mt-5">
                        <li class="ftco-animate"><a href="#"><span class="icon-twitter"></span></a></li>
                        <li class="ftco-animate"><a href="#"><span class="icon-facebook"></span></a></li>
                        <li class="ftco-animate"><a href="#"><span class="icon-instagram"></span></a></li>
                    </ul>
                </div>
            </div>


            <div class="col-md">
                <div class="ftco-footer-widget mb-4">
                    <h2 class="ftco-heading-2">Sorunuz mu var?</h2>
                    <div class="block-23 mb-3">
                        <ul>
                            <li><span class="icon icon-map-marker"></span><span class="text">Ofisimize gelin sorularınızı yüz yüze yanıtlayalım. Kızılay Avm /Ankara</span></li>
                            <li><a href="/sss"><span class="icon-pencil"></span><span class="text">Sorularınızın cevabı burada!</span></a></li>
                            <li><a href="#"><span class="icon icon-envelope"></span><span class="text">info@yourdomain.com</span></a></li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12 text-center">

                <p><!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                    Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class="icon-heart color-danger" aria-hidden="true"></i> by <a href="https://instagram.com/saaadetligunler" target="_blank">Saadet</a>
                    <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. --></p>
            </div>
        </div>
    </div>
</footer>


<!-- loader -->
<div id="ftco-loader" class="show fullscreen">
    <svg class="circular" width="48px" height="48px">
        <circle class="path-bg" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke="#eeeeee"/>
        <circle class="path" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke-miterlimit="10" stroke="#F96D00"/>
    </svg>
</div>


{% load static %}

<script src="{% static 'js/jquery.min.js' %}"></script>
<script src="{% static 'js/jquery-migrate-3.0.1.min.js' %}"></script>
<script src="{% static 'js/popper.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
<script src="{% static 'js/jquery.easing.1.3.js' %}"></script>
<script src="{% static 'js/jquery.waypoints.min.js' %}"></script>
<script src="{% static 'js/jquery.stellar.min.js' %}"></script>
<script src="{% static 'js/owl.carousel.min.js' %}"></script>
<script src="{% static 'js/jquery.magnific-popup.min.js' %}"></script>
<script src="{% static 'js/aos.js' %}"></script>
<script src="{% static 'js/jquery.animateNumber.min.js' %}"></script>
<script src="{% static 'js/bootstrap-datepicker.js' %}"></script>
<script src="{% static 'js/scrollax.min.js' %}"></script>
<script src="{% static 'js/google-map.js' %}"></script>
<script src="{% static 'js/main.js' %}"></script>

home/templates/house_detail.html
{% extends "homebase.html" %}
{% block title %}{{ house.company }} {% endblock %}
{% block keywords %}{{ house.keywords }}{% endblock %}
{% block description %}{{ house.description }}{% endblock %}



{% block header %}
    {% include 'header.html' %}
    <link rel='shortcut icon' type='image/x-icon' href='{{ setting.icon.url }}' />
{% endblock %}



{% block content %}
    <div class="hero-wrap" style="background-image: url('../static/images/bg_1.jpg');">
        <div class="overlay"></div>
        <div class="container">
            <div class="row no-gutters slider-text align-items-center justify-content-center">
                <div class="col-md-9 ftco-animate text-center">
                    <p class="breadcrumbs"><span class="mr-2"><a href="index.html">Anasayfa</a></span>
                    <h1 class="mb-3 bread">Ev Detayları</h1><a href="/category/{{ house.category_id }}/{{ house.category.slug }}">{{ house.category }}</a>
                </div>
            </div>
        </div>
    </div>

    <section class="ftco-section">
        <div class="container">
            <div class="row">
                <div class="col-lg-8">
                    <div class="row">
                        <div class="col-md-12 ftco-animate">
                            <div class="single-slider owl-carousel">
                                <div class="item">
                                    <div class="properties-img" style="background-image: url({{ house.image.url }});"></div>
                                </div>
                                {% for rs in images %}
                                    <div class="item">
                                        <div class="properties-img" style="background-image: url({{ rs.image.url }});"></div>
                                    </div>
                                {% endfor %}
                            </div>
                        </div>
                        <div class="col-md-12 Properties-single mt-4 mb-5 ftco-animate">
                            <h2>{{house.title}}</h2>
                            <p class="rate mb-4">
                                <span class="loc"><a href="#"><i class="icon-map"></i> {{house.address}}</a></span>
                            </p>
                            <p>{{ house.detail |safe}}
                            <p></p>
                        </div>
                    </div>
                </div>

                <div class="col-lg-4">
                    <h3>Yorumlar</h3>
                    {% for rs in comment %}
                    <ul class="comment-list">
                        <li class="comment">
                            <div class="comment-body">
                                <h3>{{ rs.user.first_name }}</h3>
                                <div class="fa fa-clock-o">{{ rs.create_up }}</div>
                                <p>{{ rs.comment }}<p><a href="#" class="reply">Reply</a></p>
                            </div>
                        </li>
                    </ul>
                    {% endfor %}
                </div>

            </div>

        <div class="comment-form-wrap pt-5">
            <h3 class="mb-5">Yorum Bırakın :)</h3>
            {% if messages %}
                {% for message in messages %}
                    <div class="alert alert-{{ message.tags }}" roles="alert">
                        {{ message }}
                    </div>
                {% endfor %}
            {% endif %}
            <form class ="review-form" action="/house/addcomment/{{ house.id }}" method="post">
                {% csrf_token %}
                <div>
                    <div class="form-group">
                        <label for="subject">Subject</label>
                        <input type="text" class="form-control" name="subject" id="id_subject" placeholder="Konu">
                    </div>

                    <div class="form-group">
                        <label for="comment">Message</label>
                        <textarea type="text"  class="form-control" name="comment" id="id_comment" cols="30" rows="10" placeholder="Görüşünüz"></textarea>
                    </div>
                    <div class="control-group">
                        <label class="control-label">Your Rating: <sup>*</sup></label>
                        <div class="controls">
                            <input type="radio" id="star5" name="rate" value="5"/> <label for="star5"></label>
                            <input type="radio" id="star4" name="rate" value="4"/> <label for="star4"></label>
                            <input type="radio" id="star3" name="rate" value="3"/> <label for="star3"></label>
                            <input type="radio" id="star2" name="rate" value="2"/> <label for="star2"></label>
                            <input type="radio" id="star1" name="rate" value="1"/> <label for="star1"></label>
                        </div>

                    </div>
                    <div class="form-group">
                        {% if user.id is not None %}
                            <input type="submit" value="Post Comment" class="btn py-3 px-4 btn-primary">
                        {% else %}
                            Yorum eklemek için <a href ="/login">Login</a> olunuz!
                        {% endif %}
                    </div>
                </div>
            </form>
        </div>
        </div>
    </section>


{% endblock %}

{% include 'footer.html' %}
{% block footer %} {% endblock %}

home/templates/index.html
{% extends "homebase.html" %}
{% block title %}{{ setting.title }} {% endblock %}
{% block keywords %}{{ setting.keywords }}{% endblock %}
{% block description %}{{ setting.description }}{% endblock %}



    {% block header %}
        {% include 'header.html' %}
        <link rel='shortcut icon' type='image/x-icon' href='{{ setting.icon.url }}' />
    {% endblock %}

    {% block slider %}
        {% include 'slider.html' %}
     {% endblock %}

    {% block content %}
        {% include 'content.html' %}
     {% endblock %}

    {% include 'footer.html' %}
    {% block footer %} {% endblock %}