home/urls.py
from django.urls import path

from . import views

urlpatterns = [
    # ex: /home/
    path('', views.index, name='index'),

]

myProject1/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from home import views

urlpatterns = [
    path('', include('home.urls')),
    path('house/', include('house.urls')),
    path('user/', include('user.urls')),
    path('admin/', admin.site.urls),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('hakkimizda/', views.hakkimizda, name='hakkimizda'),
    path('referanslar/', views.referanslar, name='referanslar'),
    path('iletisim/', views.iletisim, name='iletisim'),
    path('category/<int:id>/<slug:slug>/',views.category_houses, name='category_houses'),
    path('house/<int:id>/<slug:slug>/',views.house_detail, name='house_detail'),
    path('search/', views.house_search, name='house_search'),
    path('search_auto/', views.house_search_auto, name='house_search_auto'),
    path('logout/', views.logout_view, name='logout_view'),
    path('login/', views.login_view, name='login_view'),
    path('signup/', views.signup_view, name='signup_view'),
    path('sss/', views.faq, name='faq'),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

user/urls.py
from django.urls import path

from . import views

urlpatterns = [
    # ex: /home/
    path('', views.index, name='index'),
    path('update/',views.user_update, name='user_update'),
    path('password/',views.change_password, name='change_password'),
    path('comments/',views.comments, name='comments'),
    path('deletecomment/<int:id>', views.deletecomment, name='deletecomment'),
    path('addhouse/', views.addhouse, name='addhouse'),
    path('houses/', views.houses, name='houses'),
    path('houseedit/<int:id>', views.houseedit, name='houseedit'),
    path('housedelete/<int:id>', views.housedelete, name='housedelete'),
    path('houseaddimage/<int:id>', views.houseaddimage, name='houseaddimage'),
]

home/models.py
from ckeditor_uploader.fields import RichTextUploadingField
from django.contrib.auth.models import User
from django.db import models

# Create your models here.
from django.forms import ModelForm, TextInput, Textarea
from django.utils.safestring import mark_safe


class Setting(models.Model):
    STATUS = (
        ('True', 'Evet'),
        ('False', 'Hayır'),
    )
    title = models.CharField(max_length=150)
    keywords = models.CharField(blank=True,max_length=255)
    description = models.CharField(blank=True,max_length=255)
    company = models.CharField(max_length=150)
    address = models.CharField(blank=True, max_length=150)
    phone = models.CharField(blank=True, max_length=15)
    fax = models.CharField(blank=True, max_length=15)
    email = models.CharField(blank=True, max_length=50)
    smptserver = models.CharField(blank=True,max_length=20)
    smptpemail = models.CharField(blank=True,max_length=20)
    smptppassword = models.CharField(blank=True,max_length=10)
    smtpport = models.CharField(blank=True, max_length=5)
    icon = models.ImageField(blank=True, upload_to='images/')
    facebook = models.CharField(blank=True,max_length=50)
    instagram = models.CharField(blank=True,max_length=50)
    twitter = models.CharField(blank=True,max_length=50)
    aboutus = RichTextUploadingField(blank=True)
    contact = RichTextUploadingField(blank=True)
    references = RichTextUploadingField(blank=True)
    status = models.CharField(max_length=10, choices=STATUS)
    create_at = models.DateTimeField(auto_now_add=True)
    update_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title

class ContactFormMessage(models.Model):
    STATUS = (
        ('New', 'New'),
        ('Read', 'Read'),
        ('Closed','Closed'),
    )
    name = models.CharField(blank=True, max_length=20)
    email = models.CharField(blank=True, max_length=50)
    subject = models.CharField(blank=True,max_length=50)
    message = models.CharField(blank=True,max_length=255)
    status = models.CharField(max_length=10, choices=STATUS, default='New')
    ip = models.CharField(blank=True, max_length=20)
    note = models.CharField(blank=True, max_length=100)
    create_at = models.DateTimeField(auto_now_add=True)
    update_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name

class ContactFormu(ModelForm):
    class Meta:
        model = ContactFormMessage
        fields = ['name', 'email', 'subject', 'message']
        widgets = {
            'name': TextInput(attrs={'class=table table-bordered table-condensed': 'input', 'placeholder': 'Name & Surname'}),
            'email': TextInput(attrs={'class=table table-bordered table-condensed': 'input', 'placeholder': 'Email'}),
            'subject': TextInput(attrs={'class=table table-bordered table-condensed': 'input', 'placeholder': 'Email Address'}),
            'message': Textarea(attrs={'class=table table-bordered table-condensed': 'input', 'placeholder': 'Your Message', 'rows': '5'}),
        }

class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    phone = models.CharField(blank=True, max_length=20)
    address = models.CharField(blank=True, max_length=150)
    city = models.CharField(blank=True, max_length=20)
    country = models.CharField(blank=True, max_length=20)
    image = models.ImageField(blank=True, upload_to='images/users/')

    def __str__(self):
        return self.user.username

    def user_name(self):
        return self.user.first_name + ' '+self.user.last_name + ' [ ' +self.user.username + ' ] '

    def image_tag(self):
        return mark_safe('<img src="{}" height="50" />'.format(self.image.url))

    image_tag.short_description = 'Image'


class UserProfileForm(ModelForm):
    class Meta:
        model = UserProfile
        fields = ['phone', 'address', 'city', 'country', 'image']


class FAQ(models.Model):
    STATUS = (
        ('True', 'Evet'),
        ('False', 'Hayır'),
    )
    ordernumber = models.IntegerField()
    question = models.CharField(max_length=150)
    answer = models.TextField()
    status = models.CharField(max_length=10, choices=STATUS)
    create_at = models.DateTimeField(auto_now_add=True)
    update_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.question

user/models.py
from django.db import models

# Create your models here.

user/forms.py
from django import forms
from django.contrib.auth.forms import UserChangeForm
from django.contrib.auth.models import User
from django.forms import TextInput, EmailInput, Select, FileInput

from home.models import UserProfile


class UserUpdateForm(UserChangeForm):
    class Meta:
        model = User
        fields = ('username', 'email', 'first_name', 'last_name')
        widgets = {
            'username'  : TextInput(attrs={'class=form-control valid' :  'input', 'placeholder' : 'username'}),
            'email'     : EmailInput(attrs={'class=form-control valid':  'input', 'placeholder' : 'email'}),
            'first_name': TextInput(attrs={'class=form-control valid' :  'input', 'placeholder' : 'first_name'}),
            'last_name' : TextInput(attrs={'class=form-control valid' :  'input', 'placeholder' : 'last_name'}),
        }

CITY = [
    ('İstanbul', 'İstanbul'),
    ('Ankara', 'Ankara'),
    ('İzmir', 'İzmir'),

]

class ProfileUpdateForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ('phone', 'address', 'city', 'country', 'image')
        widgets = {

            'phone': TextInput(attrs={'class=form-control valid': 'input', 'placeholder': 'phone'}),
            'address': TextInput(attrs={'class=form-control valid': 'input', 'placeholder': 'address'}),
            'city': Select(attrs={'class=form-control valid': 'input', 'placeholder': 'city'}, choices= CITY),
            'country': TextInput(attrs={'class=form-control valid': 'input', 'placeholder': 'country'}),
            'image': FileInput(attrs={'class=form-control valid': 'input', 'placeholder': 'image'}),

         }

user/views.py
from django.contrib import messages
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import PasswordChangeForm
from django.http import HttpResponseRedirect
from django.shortcuts import render, redirect

# Create your views here.
import house
import user
from house.models import Category, Comment, HouseForm, House, ImageForm, Images
from home.models import UserProfile, Setting
from user.forms import UserUpdateForm, ProfileUpdateForm


@login_required(login_url='/login')
def index(request):
    category = Category.objects.all()
    current_user = request.user
    try:
        profile = UserProfile.objects.get(user_id=current_user.id)

        # return HttpResponse(profile)
        context = {'category': category,
                   'profile': profile}

        return render(request, 'user_profile.html', context)
    except:
        return HttpResponseRedirect("/")


@login_required(login_url='/login')
def user_update(request):
    if request.method == 'POST':
        user_form = UserUpdateForm(request.POST, instance=request.user)
        profile_form = ProfileUpdateForm(request.POST, request.FILES, instance=request.user.userprofile)
        if user_form.is_valid() and profile_form.is_valid():
            user_form.save()
            profile_form.save()
            messages.success(request, 'Your account has been updated!')
            return redirect('/user')
    else:
        category = Category.objects.all()
        user_form = UserUpdateForm(instance=request.user)
        profile_form = ProfileUpdateForm(instance=request.user.userprofile)
        context = {
            'category': category,
            'user_form': user_form,
            'profile_form': profile_form,
        }
        return render(request, 'user_update.html', context)


@login_required(login_url='/login')
def change_password(request):
    if request.method == 'POST':
        form = PasswordChangeForm(request.user, request.POST)
        if form.is_valid():
            user = form.save()
            update_session_auth_hash(request, user)
            messages.success(request, 'Your password was succesfully updated!')
            return redirect('/user')
        else:
            messages.error(request, 'Please correct the error below.<br>' + str(form.errors))
            return HttpResponseRedirect('/user/password')
    else:
        category = Category.objects.all()
        form = PasswordChangeForm(request.user)
        return render(request, 'change_password.html', {
            'form': form, 'category': category
        })


@login_required(login_url='/login')
def comments(request):
    category = Category.objects.all()
    current_user = request.user
    setting = Setting.objects.get(pk=1)
    comments = Comment.objects.filter(user_id=current_user.id)
    context = {
        'category': category,
        'comments': comments, 'setting': setting,
    }

    return render(request, 'user_comments.html', context)


@login_required(login_url='/login')
def deletecomment(request, id):
    current_user = request.user
    Comment.objects.filter(id=id, user_id=current_user.id).delete()
    messages.success(request, 'Comment deleted..')
    return HttpResponseRedirect('/user/comments')


@login_required(login_url='/login')
def addhouse(request):
    if request.method == 'POST':
        form = HouseForm(request.POST, request.FILES)
        if form.is_valid():
            current_user = request.user
            data = House()
            data.user_id = current_user.id
            data.title = form.cleaned_data['title']
            data.keywords = form.cleaned_data['keywords']
            data.description = form.cleaned_data['description']
            data.image = form.cleaned_data['image']
            data.category = form.cleaned_data['category']
            data.slug = form.cleaned_data['slug']
            data.detail = form.cleaned_data['detail']
            data.status = 'False'
            data.save()
            messages.success(request, 'Your House Inserted Successfuly')
            return HttpResponseRedirect('/user/houses')
        else:
            messages.success(request, 'Content Form Error :' + str(form.errors))
            return HttpResponseRedirect('/user/addhouse')
    else:
        category = Category.objects.all()
        form = HouseForm()
        context = {
            'category': category,
            'form': form,
        }
        return render(request, 'user_addhouse.html', context)


@login_required(login_url='/login')
def houseedit(request, id):
    house = House.objects.get(id=id)
    if request.method == 'POST':
        form = HouseForm(request.POST, request.FILES, instance=house)
        if form.is_valid():
            form.save()
            messages.success(request, 'Your House Updated Successfuly')
            return HttpResponseRedirect('/user/houses')
        else:
            messages.success(request, 'Content Form Error :' + str(form.errors))
            return HttpResponseRedirect('/user/houseedit/' + str(id))
    else:
        category = Category.objects.all()
        form = HouseForm(instance=house)
        context = {
            'category': category,
            'form': form,
        }
        return render(request, 'user_addhouse.html', context)


@login_required(login_url='/login')
def houses(request):
    category = Category.objects.all()
    current_user = request.user
    houses = House.objects.filter(user_id=current_user.id, status='True')
    context = {
        'category': category,
        'houses': houses,
    }
    return render(request, 'user_houses.html', context)


@login_required(login_url='/login')
def housedelete(request, id):
    current_user = request.user
    House.objects.filter(id=id, user_id=current_user.id).delete()
    messages.success(request, 'House deleted..')
    return HttpResponseRedirect('/user/houses')


def houseaddimage(request, id):
    if request.method == 'POST':
        lasturl = request.META.get('HTTP_REFERER')
        form = ImageForm(request.POST, request.FILES)
        if form.is_valid():
            data = Images()
            data.title = form.cleaned_data['title']
            data.house_id = id
            data.image = form.cleaned_data['image']
            data.save()
            messages.success(request, 'Your image has been succesfully uploaded')
            return HttpResponseRedirect(lasturl)
        else:
            messages.warning(request, 'Form Error :' + str(form.errors))
            return HttpResponseRedirect(lasturl)
    else:
        house = House.objects.get(id=id)
        images = Images.objects.filter(house_id=id)
        form = ImageForm()
        context = {
            'house': house,
            'images': images,
            'form': form,
        }
        return render(request, 'houseImage_gallery.html', context)

user/templates/change_password.html
{% extends "homebase.html" %}

{% block title %} {{ profile.user_name }} Profile {% endblock %}
{% block keywords %} {{ setting.keywords }} {% endblock %}
{% block description %} {{ setting.description }} {% endblock %}

{% block head %}
    <link rel='shortcut icon' type='image/x-icon' href='{{ setting.icon.url }}'/>{% endblock %}

{% block content %}


    <!-- bradcam_area_start -->
    <div class="bradcam_area breadcam_bg overlay2">
        <h3>Change Password</h3>
    </div>
    <!-- bradcam_area_end -->

    <section class="contact-section">
        <div class="container">
            <div class="row">
                <div class="col-lg-5">
                    {% include "user_panel.html" %}
                </div>
                <div class="col-lg-7">
                    <div class="section_title">
                        <h3 class="contact-title">User Information</h3>
                    </div>
                    <div class="section-content">
                        {% if messages %}
                            {% for message in messages %}
                                <div style="color:red; font-size: medium">
                                    {{ message|safe }}
                                </div>
                            {% endfor %}
                        {% endif %}
                        <form method="POST">
                            {% csrf_token %}
                            {% for field in form %}
                                <p>
                                    {{ field.label_tag }}<br>
                                    {{ field }}
                                    {% if field.help_text %}
                                        <small style="color: grey">{{ field.help_text }}</small>
                                    {% endif %}
                                    {% for error in field.errors %}
                                        <p style="">{{ error }}</p>
                                    {% endfor %}
                                </p>
                            {% endfor %}
                            <button class="btn btn-outline-info" type="submit">Update</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- ================ contact section end ================= -->
{% endblock %}

user/templates/houseImage_gallery.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>house Gallery</title>
</head>
<body>
<h2>{{ house.title }}</h2>
<hr>
{% if messages %}
    {% for message in messages %}
        <div class="alert alert-{{ message.tags }}" role="alert">
            {{ message|safe }}
        </div>
    {% endfor %}
{% endif %}
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <input type="hidden" name="house_id" value="{{ house.id }}">
    <label for="id_title">Title:</label>
    <input type="text" name="title" class="input" placeholder="title" maxlength="50" id="id_title"></p>
    <label for="id_image">Image:</label>
    <input type="file" name="image" class="input" placeholder="image" accept="image/*" id="id_image"></p>
    <button class="genric-btn danger circle" type="submit">Upload Image</button>
</form>
<hr>
<h4>Yüklenen Resimler</h4>
{% for rs in images %}
    <img src="{{ rs.image.url }}" height="200">
{% endfor %}
</body>
</html>

user/templates/user_addhouse.html
{% extends "homebase.html" %}

{% block title %} {{ profile.user_name }} Profile {% endblock %}
{% block keywords %} {{ setting.keywords }} {% endblock %}
{% block description %} {{ setting.description }} {% endblock %}

{% block head %}
    <link rel='shortcut icon' type='image/x-icon' href='{{ setting.icon.url }}'/>
    {% load static %}
    <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/2.2.4/jquery.min.js"></script>
    <script type="text/javascript" src="{% static "ckeditor/ckeditor-init.js" %}"></script>
    <script type="text/javascript" src="{% static "ckeditor/ckeditor/ckeditor.js" %}"></script>
{% endblock %}


{% block content %}


    <!-- bradcam_area_start -->
    <div class="bradcam_area breadcam_bg overlay2">
        <h3>User Houses</h3>
    </div>
    <!-- bradcam_area_end -->

    <section class="contact-section">
        <div class="container">
            <div class="row">
                <div class="col-lg-3">
                    {% include "user_panel.html" %}
                </div>
                <div class="col-lg-9">
                    <h3 class="contact-title">Add House</h3>
                    <div class="section-content">
                        {% if messages %}
                            {% for message in messages %}
                                <div class="alert alert-{{ message.tags }}" role="alert">
                                    {{ message }}
                                </div>
                            {% endfor %}
                        {% endif %}
                        <form action="" method="POST" enctype="multipart/form-data">
                            {% csrf_token %}
                            <fieldset class="form-group">
                                {{ form.media }}
                                {{ form.as_p }}
                            </fieldset>
                            <div class="form-group">
                                <button class="genric-btn danger circle" type="submit">SAVE</button>
                            </div>
                        </form>
                    </div>
                </div>

            </div>
        </div>
    </section>
    <!-- ================ contact section end ================= -->
{% endblock %}

user/templates/user_comments.html
{% extends "homebase.html" %}

{% block title %} House Comments {% endblock %}
{% block keywords %} {{ setting.keywords }} {% endblock %}
{% block description %} {{ setting.description }} {% endblock %}

{% block head %}
    <link rel='shortcut icon' type='image/x-icon' href='{{ setting.icon.url }}'/>{% endblock %}



{% block content %}


    <!-- bradcam_area_start -->
    <div class="bradcam_area breadcam_bg overlay2">
        <h3></h3>
    </div>
    <!-- bradcam_area_end -->
    {% if messages %}
        {% for message in messages %}
            <div class="alert alert-{{ message.tags }}" roles="alert">
                {{ message }}
            </div>
        {% endfor %}
    {% endif %}
    <section class="contact-section">
        <div class="container">
            <div class="row">
                <div class="col-lg-3">
                    {% include "user_panel.html" %}
                </div>
                <div class="col-lg-9">
                    <h3 class="contact-title">User Comments</h3>
                    <table class="table table-bordered table-condensed">
                        <tr>
                            <th class="text_left">House</th>
                            <th class="text_left">Rate</th>
                            <th class="text_left">Subject</th>
                            <th class="text_left">Comment</th>
                            <th class="text_left">Status</th>
                            <th class="text_left">Date</th>
                            <th class="text_left">Detail</th>
                        </tr>
                        {% for rs in comments %}
                            <tr>
                                <td class="text-left">
                                    <a href="/house/{{ rs.house_id }}/{{ rs.house.slug }}">
                                        <strong>{{ rs.house.title }}</strong>
                                    </a>
                                </td>
                                <td class="text-left">{{ rs.rate }}</td>
                                <td class="text-left">{{ rs.subject }}</td>
                                <td class="text-left">{{ rs.comment }}</td>
                                <td class="text-left">{{ rs.status }}</td>
                                <td class="text-left">{{ rs.create_at }}</td>
                                <td class="text-left"><a class="genric-btn danger circle"
                                                         href="/user/deletecomment/{{ rs.id }}"
                                                         onclick="return confirm('Will be Delete ! Are you sure?')">Delete</a>
                                </td>
                            </tr>
                        {% endfor %}
                    </table>
                </div>
            </div>
        </div>
    </section>
    <!-- ================ contact section end ================= -->
{% endblock %}

user/templates/user_houses.html
{% extends "homebase.html" %}

{% block title %} {{ profile.user_name }} Profile {% endblock %}
{% block keywords %} {{ setting.keywords }} {% endblock %}
{% block description %} {{ setting.description }} {% endblock %}

{% block head %}
    <link rel='shortcut icon' type='image/x-icon' href='{{ setting.icon.url }}'/>{% endblock %}



{% block content %}
    {% load static %}


    <!-- bradcam_area_start -->
    <div class="bradcam_area breadcam_bg overlay2">
        <h3></h3>
    </div>
    <!-- bradcam_area_end -->

    <section class="contact-section">
        <div class="container">
            <div class="row">
                <div class="col-lg-3">
                    {% include "user_panel.html" %}
                </div>
                <div class="col-lg-9">
                    <h3 class="contact-title">User Houses<a class="genric-btn danger circle" href="/user/addhouse/">Add
                        House</a>
                    </h3>
                    <table class="table table-bordered table-condensed">
                        <tr>
                            <th class="text_left">Image</th>
                            <th class="text_left">Title</th>
                            <th class="text_left">Category</th>
                            <th class="text_left">Gallery</th>
                            <th class="text_left">Date</th>
                            <th class="text_left">Detail</th>
                        </tr>
                        {% for rs in houses %}
                            <tr>

                                <td class="text-left">
                                    <a href="/house/{{ rs.id }}/{{ rs.slug }}">
                                        <img src="{{ rs.image.url }}" style="height: 30px">
                                    </a>
                                </td>
                                <td class="text-left">
                                    <a href="/house/{{ rs.id }}/{{ rs.slug }}">
                                        {{ rs.title }}
                                    </a>
                                </td>
                                <td class="text-left">{{ rs.category }}</td>


                                <td class="text-left">
                                    <a href="javascript:;"
                                       onclick="window.open('/user/houseaddimage/{{ rs.id }}', 'galley', 'height=600, width=800, top=50, left=150')">
                                        <img src="{% static '/images/gallery.png' %}" style="height: 50px;">
                                    </a>
                                </td>


                                <td class="text-left">{{ rs.create_at }}</td>
                                <td class="text-left"><a class="genric-btn danger circle"
                                                         href="/user/houseedit/{{ rs.id }}">Edit</a>
                                </td>
                                <td class="text-left"><a onclick="return confirm('Will be Delete ! Are you sure?')"
                                                         class="genric-btn danger circle"
                                                         href="/user/housedelete/{{ rs.id }}">Delete</a>
                                </td>
                            </tr>
                        {% endfor %}
                    </table>
                </div>
            </div>
        </div>
    </section>
    <!-- ================ contact section end ================= -->
{% endblock %}

user/templates/user_panel.html
<div class="sidebar-box ftco-animate">
    <div class="categories">
        <h3>Kullanıcı Paneli</h3>
        <li><a href="/user">Kullanıcı Profili </a></li>
        <li><a href="/user/comments">Yorumlarım </a></li>
        <li><a href=/user/houses>Evlerim </a></li>
        <li><a href="/logout">Çıkış </a></li>
    </div>
</div>

user/templates/user_profile.html
{% extends "homebase.html" %}
{% block title %}User Profile{{ profile.user_name}} {% endblock %}
{% block keywords %}{{ setting.keywords }}{% endblock %}
{% block description %}{{ setting.description }}{% endblock %}



{% block header %}
    {% include 'header.html' %}
    <link rel='shortcut icon' type='image/x-icon' href='{{ setting.icon.url }}' />
{% endblock %}



{% block content %}
    <div class="hero-wrap" style="background-image: url('../static/images/bg_0.jpg');">
        <div class="overlay"></div>
        <div class="container">
            <div class="row no-gutters slider-text align-items-left justify-content-left">

                <div class="col-md-9 ftco-animate text-left">
                    <p class="breadcrumbs"><span class="mr-2"><a href="/">Anasayfa</a></span></p>
                    <h1 class="mb-3 bread">{{ categorydata.title }}</h1>
                </div>

            </div>
        </div>
    </div>



    <section class="ftco-section ftco-degree-bg">
        <div class="container">
            <div class="row">
                <div class="col-lg-4 ftco-animate">
                    {% include "user_panel.html" %}
                </div>

                <div class="col-lg-8 ftco-animate">
                    <div class="sidebar-box ftco-animate">
                        <h3>Kullanıcı Bİlgileri</h3>
                        <table class="shopping-house-table table">
                            <tr class="table-row">
                                <th class="text_center">
                                    <a href="/user/update" class="btn py-3 px-4 btn-primary">Update Profile</a>
                                    <a href="/user/password" class="btn py-3 px-4 btn-primary">Change Password</a>
                                     <td class="text-center"><img src="{{ profile.image.url }}"></td>
                                </th>
                            </tr>
                            <tr>
                                <th class="text-left">İsim Soyisim</th>
                                <td class="text-left">{{profile.user_name}}</td>
                            </tr>
                            <tr>
                                <th class="text-left">Email</th>
                                <td class="text-left">{{profile.email}}</td>
                            </tr>
                            <tr>
                                <th class="text-left">Telefon</th>
                                <td class="text-left">{{profile.phone}}</td>
                            </tr>
                            <tr>
                                <th class="text-left">Adres</th>
                                <td class="text-left">{{profile.address}}</td>
                            </tr>
                            <tr>
                                <th class="text-left">Şehir</th>
                                <td class="text-left">{{profile.city}}</td>
                            </tr>
                            <tr>
                                <th class="text-left">Ülke</th>
                                <td class="text-left">{{profile.country}}</td>
                            </tr>

                        </table>
                    </div>
                </div>
            </div>
        </div>
    </section>





{% endblock %}


{% include 'footer.html' %}



{% block footer %} {% endblock %}